version: '3.9'
services:
  client:
    tty: true
    platform: linux/amd64
    container_name: floact_client
    build:
      context: .
      dockerfile: dockerfiles/client.Dockerfile
      args:
        - FLOACT_ENV=$FLOACT_ENV
        - FLOACT_NEXT_TELEMETRY_DISABLED=$FLOACT_NEXT_TELEMETRY_DISABLED
        - FLOACT_CLIENT_PORT=$FLOACT_CLIENT_PORT
    ports:
      - 3000:3000
    env_file:
      - envs/.env.production.docker
  server:
    tty: true
    platform: linux/amd64
    container_name: floact_server
    build:
      context: .
      dockerfile: dockerfiles/server.Dockerfile 
      args:
        - FLOACT_ENV=$FLOACT_ENV
        - FLOACT_SERVER_FLASK_PORT=$FLOACT_SERVER_FLASK_PORT
        - FLOACT_SERVER_FLASK_HOST=$FLOACT_SERVER_FLASK_HOST
    ports:
      - '3001:3001'
    env_file:
      - envs/.env.production.docker
