version: '3.9'
services:
  uilib:
    build:
      context: ./apps/uilib
      dockerfile: Dockerfile
    env_file:
      - envs/.env.production
  client:
    depends_on:
      - "uilib"
    container_name: floact_client
    build:
      context: ./apps/client
      dockerfile: Dockerfile
    ports:
      - '3004:3004'
    env_file:
      - envs/.env.production
    restart: always
