version: '3.9'
services:
  client:
    platform: linux/amd64
    container_name: floact_client
    build:
      context: .
      dockerfile: dockerfiles/client.dockerfile 
    ports:
      - '3004:3004'
    env_file:
      - envs/.env.production
    restart: always
