/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface DocReadme {
        "apiTestString": string;
    }
}
declare global {
    interface HTMLDocReadmeElement extends Components.DocReadme, HTMLStencilElement {
    }
    var HTMLDocReadmeElement: {
        prototype: HTMLDocReadmeElement;
        new (): HTMLDocReadmeElement;
    };
    interface HTMLElementTagNameMap {
        "doc-readme": HTMLDocReadmeElement;
    }
}
declare namespace LocalJSX {
    interface DocReadme {
        "apiTestString"?: string;
    }
    interface IntrinsicElements {
        "doc-readme": DocReadme;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "doc-readme": LocalJSX.DocReadme & JSXBase.HTMLAttributes<HTMLDocReadmeElement>;
        }
    }
}
